# Generated by Django 5.0.1 on 2026-06-01 12:04

import django.db.models.deletion
import offline_payments.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_orderrequest_active_status'),
        ('sales', '0008_storeorder_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflinePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('currency', models.CharField(default='IRR', max_length=10)),
                ('status', models.CharField(choices=[('pending_receipt', 'در انتظار بارگذاری فیش'), ('pending_review', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('expired', 'منقضی شده'), ('locked', 'قفل شده')], db_index=True, default='pending_receipt', max_length=24)),
                ('rejection_count', models.PositiveSmallIntegerField(default=0)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_deadline', models.DateTimeField(db_index=True)),
                ('target_iban_id', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offline_payments', to='orders.order')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_offline_payments', to=settings.AUTH_USER_MODEL)),
                ('store_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offline_payments', to='sales.storeorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OfflinePaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='offline_payments.offlinepayment')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OfflinePaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=64)),
                ('recipient', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('sent', 'ارسال شده'), ('failed', 'ناموفق'), ('skipped', 'ارسال نشده')], max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='offline_payments.offlinepayment')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OfflinePaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=offline_payments.models.receipt_upload_path)),
                ('reference_number', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=16)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='offline_payments.offlinepayment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_offline_payment_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='offlinepayment',
            index=models.Index(fields=['user', 'status', 'created_at'], name='offline_pay_user_id_7ea347_idx'),
        ),
        migrations.AddIndex(
            model_name='offlinepayment',
            index=models.Index(fields=['status', 'payment_deadline'], name='offline_pay_status_388b66_idx'),
        ),
        migrations.AddConstraint(
            model_name='offlinepayment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('marketplace_order__isnull', True), ('store_order__isnull', False)), models.Q(('marketplace_order__isnull', False), ('store_order__isnull', True)), _connector='OR'), name='offline_payment_exactly_one_source'),
        ),
    ]
