# Generated by Django 5.0.1 on 2026-06-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_payments', '0002_satnabankaccount_satnabankaccountauditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinepaymentnotification',
            name='dedupe_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='offlinepaymentnotification',
            name='status',
            field=models.CharField(choices=[('pending', 'در صف ارسال'), ('sent', 'ارسال شده'), ('failed', 'ناموفق'), ('skipped', 'ارسال نشده')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='offlinepaymentnotification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('payment', 'dedupe_key'), name='offline_payment_notification_unique_dedupe'),
        ),
    ]
