# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offline_payments", "0003_offlinepaymentnotification_dedupe_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offlinepaymentreceipt",
            name="amount",
            field=models.BigIntegerField(default=0),
        ),
    ]
