# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offline_payments", "0004_offlinepaymentreceipt_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offlinepaymentreceipt",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار بررسی"),
                    ("approved", "تایید شده"),
                    ("rejected", "رد شده"),
                    ("reversed", "برگشت خورده"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
