# Generated by Django 5.0.1 on 2026-06-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='کاوکس', max_length=120)),
                ('marketplace_enabled', models.BooleanField(default=False)),
                ('featured_loads_enabled', models.BooleanField(default=True)),
                ('export_enabled', models.BooleanField(default=True)),
                ('offers_enabled', models.BooleanField(default=True)),
                ('blog_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
