# Generated by Django 5.0.1 on 2026-06-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitesettings_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_oauth_client_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
