# Generated by Django 5.0.1 on 2026-06-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_google_oauth_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_tag_manager_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='openai_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='openai_content_model',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
