# Generated by Django 5.0.1 on 2026-06-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_google_tag_manager_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_scripts',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='head_scripts',
            field=models.TextField(blank=True, default=''),
        ),
    ]
