# Generated by Django 5.0.1 on 2026-06-16 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoAssistantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('assistant_name', models.CharField(default='متخصص سئو', max_length=80)),
                ('greeting', models.TextField(blank=True, default='سلام 👋 من متخصص سئوی شما هستم. بپرس: می\u200cخواهی یک صفحه/سایت را آدیت کنم، title/meta بنویسم، استراتژی کلمات کلیدی و محتوا بدهم، یا برای جستجوی هوش مصنوعی (AI Overviews/GEO) بهینه کنیم؟')),
                ('persona', models.TextField(blank=True, default='تو «متخصص ارشد سئو» هستی؛ یک مشاور باتجربهٔ SEO که سال\u200cها در نقش agency و in-house کار کرده. همیشه فارسی پاسخ می\u200cدهی (اصطلاحات سئو به انگلیسی) و مختصر، عملی و اولویت\u200cبندی\u200cشده جواب می\u200cدهی.\nاصول کاری:\n- «اول برای کاربر، بعد برای موتور جستجو» بهینه کن.\n- فقط بر اساس «دانش سئو» (که در پرامپت تزریق می\u200cشود) و دادهٔ واقعیِ صفحه (ابزار fetch_page_seo) پاسخ بده؛ از خودت توصیهٔ بی\u200cپایه نساز.\n- اعداد و حدود را دقیق بگو (title ≤۶۰ کاراکتر، meta ۱۵۰–۱۶۰، یک H1 در هر صفحه، INP ≤۲۰۰ms و ...).\n- همیشه اصولِ پایه را با لایهٔ ۲۰۲۶ (AI Overviews، GEO/AEO، E-E-A-T با Experience، entities) تکمیل کن.\n- هرگز رتبهٔ تضمینی قول نده؛ بازهٔ زمانی واقع\u200cبینانه بده (سئو ~۳ ماه برای شروع اثر).\n- یافته\u200cها را به Quick wins و Complex تقسیم کن و پیاده\u200cسازی را متناسب با استک سایت توضیح بده.')),
                ('site_context', models.TextField(blank=True, default='سایت هدف: تیرکسا (Tirexa).\nاستک: بک\u200cاند Django/DRF + فرانت\u200cاند Next.js؛ دیپلوی روی سرور اوبونتو با IP ایران (systemd: gunicorn + next + nginx).\n🚨 بزرگ\u200cترین بلاکر سئو (اولویت صفر): IP ایران باعث می\u200cشود بازدیدکنندهٔ خارجی صفحهٔ سفید بگیرد و احتمالاً Googlebot هم نتواند سایت را crawl/index کند. تا حل نشدن این (دامنه + CDN جهانی با HTTPS لبه و rebuild فرانت با NEXT_PUBLIC_* مبتنی بر دامنه)، هیچ تاکتیک سئوی دیگری اثر کامل ندارد. در هر آدیت، اول وضعیت crawlability/index و دامنه/CDN/HTTPS را چک کن.\nنکات Next.js: رندر SSR/SSG (نه فقط CSR) تا محتوا برای ربات دیده شود؛ متادیتا با Metadata API؛ تولید sitemap.xml و robots.txt؛ canonical و در صورت چندزبانه\u200cبودن hreflang.')),
                ('openai_base_url', models.CharField(default='https://api.avalai.ir/v1', max_length=255)),
                ('chat_model', models.CharField(default='gpt-4o-mini', max_length=80)),
                ('embedding_model', models.CharField(default='text-embedding-3-small', max_length=80)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.2, max_digits=3)),
                ('max_context_chunks', models.PositiveSmallIntegerField(default=8)),
                ('max_tool_iterations', models.PositiveSmallIntegerField(default=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات دستیار سئو',
                'verbose_name_plural': 'تنظیمات دستیار سئو',
            },
        ),
        migrations.CreateModel(
            name='SeoConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('open', 'باز'), ('closed', 'بسته')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'گفتگوی سئو',
                'verbose_name_plural': 'گفتگوهای سئو',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SeoKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(choices=[('base', 'پایه (اصول)'), ('2026', 'به\u200cروز ۲۰۲۶'), ('custom', 'سفارشی (ادمین)')], default='custom', max_length=10)),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('topic', models.CharField(blank=True, default='عمومی', max_length=120)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=80)),
                ('embedded_hash', models.CharField(blank=True, default='', max_length=64)),
                ('embedded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دانش سئو',
                'verbose_name_plural': 'دانش سئو',
                'ordering': ['layer', 'source', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['layer', 'is_active'], name='seo_assista_layer_1b233d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SeoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'کاربر'), ('assistant', 'دستیار'), ('tool', 'ابزار')], max_length=12)),
                ('content', models.TextField(blank=True, default='')),
                ('tool_name', models.CharField(blank=True, default='', max_length=60)),
                ('tool_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='seo_assistant.seoconversation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
