# Generated by Django 5.0.1 on 2026-06-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoassistantsettings',
            name='openai_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
