# Generated by Django 5.0.1 on 2026-06-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_assistant', '0002_seoassistantsettings_openai_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoassistantsettings',
            name='site_context',
            field=models.TextField(blank=True, default='سایت هدف: کاوکس (kavex.ir) — بازار آنلاین آهن و فولاد، پایگاه اصفهان، فروش عمدهٔ ورق و مقاطع.\nاستک: بک\u200cاند Django/DRF + فرانت\u200cاند Next.js (SSR/SSG)، سرور اوبونتو (systemd: gunicorn + next + nginx).\n✅ دامنه + HTTPS + CDN حل شده: سایت روی دامنهٔ kavex.ir پشتِ Cloudflare با HTTPS لبه فعال است. پس بلاکرِ قدیمیِ «IP ایران → صفحهٔ سفید / عدم crawl» دیگر برقرار نیست؛ آن را به\u200cعنوان بلاکر مطرح نکن مگر شواهدِ زندهٔ صفحه خلافش را نشان دهد.\nزیرساختِ سئوی پیاده\u200cشده (قبل از پیشنهادِ افزودن، با schema_types ابزار تطبیق بده): sitemap.xml + robots.txt؛ صفحاتِ محصول و لندینگ SSR با generateMetadata؛ و اسکیماهای خودکار: Organization (layout)، BreadcrumbList (همه\u200cجا)، FAQPage (هر لندینگ که بخشِ «سوالات متداول» در بدنه داشته باشد)، Product/Offer فقط روی محصول/لندینگِ قیمت\u200cدار (IRR + priceValidUntil). پس اگر صفحه\u200cای قیمت ندارد، نبودِ Product schema عمدی است نه ایراد.\nتمرکزِ فعلیِ آدیت\u200cها: عمقِ محتوا، تازگیِ جدول قیمت روزانه، H1/title کلمه\u200cمحور (ترکیبِ «خرید» + «قیمت»)، لینک\u200cسازیِ داخلیِ سیلو (لندینگ\u200cهای خواهر)، و بهینه\u200cسازی برای AI Overviews/GEO.'),
        ),
    ]
