# Generated by Django 5.0.1 on 2026-07-13 20:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_assistant', '0003_alter_seoassistantsettings_site_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seoassistantsettings',
            name='request_timeout_seconds',
            field=models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(110)]),
        ),
        migrations.CreateModel(
            name='SeoChatRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'در حال پردازش'), ('completed', 'تکمیل\u200cشده'), ('cancelled', 'لغوشده'), ('failed', 'ناموفق')], default='running', max_length=12)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('reply', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests', to='seo_assistant.seoconversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_chat_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست گفتگوی سئو',
                'verbose_name_plural': 'درخواست\u200cهای گفتگوی سئو',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='seomessage',
            name='chat_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='seo_assistant.seochatrequest'),
        ),
    ]
