# Generated by Codex on 2026-01-20

from django.db import migrations
from django.utils import timezone


def forwards(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    UserRole = apps.get_model("accounts", "UserRole")
    for profile in Profile.objects.select_related("user").all():
        user = profile.user
        UserRole.objects.get_or_create(
            user=user,
            role="BUYER",
            defaults={"is_active": True, "activated_at": timezone.now()},
        )
        if profile.role in ("SELLER", "BOTH"):
            UserRole.objects.get_or_create(
                user=user,
                role="SELLER",
                defaults={"is_active": True, "activated_at": timezone.now()},
            )


def backwards(apps, schema_editor):
    UserRole = apps.get_model("accounts", "UserRole")
    UserRole.objects.filter(role__in=["BUYER", "SELLER"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_kycrequest_kycdocument_userrole"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
