# Generated by Django 5.0.1 on 2026-02-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('WAREHOUSE_MANAGER', 'Warehouse Manager'), ('CUTTER', 'Cutter'), ('DRIVER', 'Driver'), ('QC', 'Quality Control'), ('STRUCTURAL_DESIGNER', 'Structural Designer'), ('ADMIN', 'Admin')], max_length=32),
        ),
    ]
