# Generated by Codex on 2026-02-17

from django.db import migrations
from django.utils import timezone


def forwards(apps, schema_editor):
    UserRole = apps.get_model("accounts", "UserRole")
    UserRole.objects.filter(role="BUYER", is_active=False).update(
        is_active=True,
        activated_at=timezone.now(),
    )


def backwards(apps, schema_editor):
    # Keep data as-is on rollback to avoid accidental access regression.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_userrole_role"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
