# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_activate_buyer_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("BUYER", "Buyer"),
                    ("SELLER", "Seller"),
                    ("WAREHOUSE_MANAGER", "Warehouse Manager"),
                    ("CUTTER", "Cutter"),
                    ("DRIVER", "Driver"),
                    ("CARRIER", "Carrier"),
                    ("QC", "Quality Control"),
                    ("STRUCTURAL_DESIGNER", "Structural Designer"),
                    ("ADMIN", "Admin"),
                ],
                max_length=32,
            ),
        ),
    ]
