# Generated by Django 5.0.1 on 2026-04-24 17:33

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دسته')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان خبر')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('content', ckeditor.fields.RichTextField(verbose_name='محتوا')),
                ('thumbnail', models.ImageField(upload_to='blog/thumbs/', verbose_name='تصویر شاخص')),
                ('meta_title', models.CharField(blank=True, help_text='حداکثر ۷۰ کاراکتر', max_length=70, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='حداکثر ۱۶۰ کاراکتر', max_length=160, null=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_time', models.PositiveIntegerField(default=0, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='posts', to='blog.category', verbose_name='دسته\u200cبندی\u200cها')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['slug'], name='blog_post_slug_cdb902_idx'), models.Index(fields=['published_at'], name='blog_post_publish_698bc0_idx')],
            },
        ),
    ]
