# Generated by Django 5.0.1 on 2026-05-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_siteseosettings_post_custom_schema_post_excerpt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_blocks',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
