# Generated by Django 5.0.1 on 2026-06-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_homepageslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('specification', models.CharField(blank=True, default='', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='featured-loads/')),
                ('available_quantity', models.CharField(blank=True, default='', max_length=120)),
                ('min_order_quantity', models.CharField(blank=True, default='', max_length=120)),
                ('origin', models.CharField(blank=True, default='', max_length=255)),
                ('delivery_time', models.CharField(blank=True, default='', max_length=120)),
                ('quality_grade', models.CharField(blank=True, default='', max_length=255)),
                ('loading_cost_note', models.CharField(blank=True, default='', max_length=255)),
                ('settlement_method', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.CharField(blank=True, default='', max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('cta_label', models.CharField(blank=True, default='', max_length=120)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'بار ویژه',
                'verbose_name_plural': 'بارهای ویژه',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
