# Generated by Django 5.0.1 on 2026-06-07 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_featuredload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedLoadAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('origin', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_load_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'هشدار بار ویژه',
                'verbose_name_plural': 'هشدارهای بار ویژه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedLoadAlertMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'ایمیل'), ('SMS', 'پیامک')], default='EMAIL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('SENT', 'ارسال\u200cشده'), ('FAILED', 'ناموفق'), ('SKIPPED', 'نادیده\u200cگرفته\u200cشده')], db_index=True, default='PENDING', max_length=20)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='blog.featuredloadalert')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_matches', to='blog.featuredload')),
            ],
            options={
                'verbose_name': 'تطبیق هشدار بار ویژه',
                'verbose_name_plural': 'تطبیق\u200cهای هشدار بار ویژه',
                'ordering': ['-created_at'],
                'unique_together': {('alert', 'load')},
            },
        ),
    ]
