# Generated by Django 5.0.1 on 2026-06-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_seed_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=40)),
                ('slug', models.SlugField(allow_unicode=True, max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, default='', max_length=300)),
                ('intro', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('steel_grade', models.CharField(blank=True, default='', max_length=80)),
                ('meta_title', models.CharField(blank=True, default='', max_length=200)),
                ('meta_description', models.CharField(blank=True, default='', max_length=300)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'لندینگ',
                'verbose_name_plural': 'لندینگ\u200cها',
                'ordering': ['family', 'sort_order', 'id'],
                'unique_together': {('family', 'slug')},
            },
        ),
    ]
