"""
Django settings for tg1 project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l4uxb3a8v8v^f26ehu4x6k#8@37mi7cqx42@$wx+mle#(hra2y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'django_extensions',
    'core',
    'products',
    'mptt',
    'companypage',
    "corsheaders",
    'accounts',
    'tags',
    
]
# Optionally enable drf-spectacular if it's installed in the environment.
# This avoids import-time failures when running management commands before
# installing development-only packages.
try:
    import drf_spectacular  # type: ignore
except Exception:
    SPECTACULAR_AVAILABLE = False
else:
    SPECTACULAR_AVAILABLE = True
    INSTALLED_APPS.append('drf_spectacular')
REST_FRAMEWORK = {
    # Pagination global (در صورت تمایل می‌توان کلاس سفارشی هم انتخاب کرد)
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,

    # Filtering / Search / Ordering backends
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],

    # (اختیاری) auth / permissions مناسب توسعه:
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],

    # Authentication: include JWT (simplejwt) and session auth as fallbacks
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),

}

# Configure drf-spectacular schema class only if the package is available
if globals().get('SPECTACULAR_AVAILABLE'):
    REST_FRAMEWORK['DEFAULT_SCHEMA_CLASS'] = 'drf_spectacular.openapi.AutoSchema'
    SPECTACULAR_SETTINGS = {
        'TITLE': 'kavehmetal API',
        'DESCRIPTION': 'API schema for the kavehmetal backend',
        'VERSION': '1.0.0',
    }
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tg1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tg1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2', # موتور دیتابیس
        'NAME': 'alibackend_db', # نام دیتابیس (همان که در docker-compose.yml تعریف کردید)
        'USER': 'ariakh', # نام کاربری (همان که در docker-compose.yml تعریف کردید)
        'PASSWORD': '123456', # رمز عبور (همان که در docker-compose.yml تعریف کردید)
        'HOST': 'localhost', # نام سرویس دیتابیس در docker-compose.yml (نه localhost!)
        'PORT': '5432', # پورت پیش فرض PostgreSQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

# development email backend: print emails to console
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# used by registration to build verification link
FRONTEND_BASE = "http://localhost:3000"
DEFAULT_FROM_EMAIL = "noreply@example.com"

# Verification resend rate-limit defaults
VERIFICATION_RESEND_WINDOW_HOURS = 24
VERIFICATION_RESEND_MAX = 5