"""
Django settings for tg1 project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "change-me-local-dev-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'django_extensions',
    'django_ckeditor_5',
    # ************************
    'core',
    'products',
    'mptt',
    'companypage',
    "corsheaders",
    'accounts',
    'tags',
    'orders',
    'sales',
    'offline_payments',
    'blog',
    'assistant',

]
# Optionally enable drf-spectacular if it's installed in the environment.
# This avoids import-time failures when running management commands before
# installing development-only packages.
try:
    import drf_spectacular  # type: ignore
except Exception:
    SPECTACULAR_AVAILABLE = False
else:
    SPECTACULAR_AVAILABLE = True
    INSTALLED_APPS.append('drf_spectacular')
REST_FRAMEWORK = {
    # Pagination global (در صورت تمایل می‌توان کلاس سفارشی هم انتخاب کرد)
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,

    # Filtering / Search / Ordering backends
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],

    # (اختیاری) auth / permissions مناسب توسعه:
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],

    # Authentication: include JWT (simplejwt) and session auth as fallbacks
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),

}

# KYC document validation
KYC_DOCUMENT_MAX_SIZE_MB = int(os.environ.get("KYC_DOCUMENT_MAX_SIZE_MB", 10))
KYC_DOCUMENT_ALLOWED_EXTENSIONS = [".pdf", ".zip"]
KYC_DOCUMENT_ALLOWED_MIME_TYPES = [
    "application/pdf",
    "application/zip",
    "application/x-zip-compressed",
    "multipart/x-zip",
]
ORDER_REQUEST_DOC_MAX_SIZE_MB = int(os.environ.get("ORDER_REQUEST_DOC_MAX_SIZE_MB", 10))
ORDER_REQUEST_DOC_ALLOWED_EXTENSIONS = [".pdf", ".zip"]
ORDER_REQUEST_DOC_ALLOWED_MIME_TYPES = [
    "application/pdf",
    "application/zip",
    "application/x-zip-compressed",
    "multipart/x-zip",
]

# Configure drf-spectacular schema class only if the package is available
if globals().get('SPECTACULAR_AVAILABLE'):
    REST_FRAMEWORK['DEFAULT_SCHEMA_CLASS'] = 'drf_spectacular.openapi.AutoSchema'
    SPECTACULAR_SETTINGS = {
        'TITLE': 'kavehmetal API',
        'DESCRIPTION': 'API schema for the kavehmetal backend',
        'VERSION': '1.0.0',
    }
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tg1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tg1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.postgresql_psycopg2'),
        'NAME': os.environ.get('DB_NAME', 'alibackend_db'),
        'USER': os.environ.get('DB_USER', 'ariakh'),
        'PASSWORD': os.environ.get('DB_PASSWORD', '123456'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CORS_ALLOWED_ORIGINS", "http://localhost:3000").split(",")
    if origin.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

# Transactional email settings. Development prints messages unless explicitly overridden.
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "25"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "0") == "1"
if DEBUG and "EMAIL_BACKEND" not in os.environ:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# used by registration to build verification link
FRONTEND_BASE = os.environ.get("FRONTEND_BASE", "http://localhost:3000")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@example.com")

# Verification resend rate-limit defaults
VERIFICATION_RESEND_WINDOW_HOURS = 24
VERIFICATION_RESEND_MAX = 5

# Google Sign-In: همان Client ID وب که در فرانت NEXT_PUBLIC_GOOGLE_CLIENT_ID است.
# تا وقتی خالی باشد، اندپوینت /api/auth/google/ غیرفعال است (503).
GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_OAUTH_CLIENT_ID", "")

CKEDITOR_5_FILE_STORAGE = "tg1.storage_backends.CKEditor5Storage"

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
OPENAI_CONTENT_MODEL = os.environ.get("OPENAI_CONTENT_MODEL", "gpt-5-mini")
OPENAI_API_TIMEOUT_SECONDS = int(os.environ.get("OPENAI_API_TIMEOUT_SECONDS", "30"))
OFFLINE_PAYMENT_BANK_ACCOUNTS_JSON = os.environ.get("OFFLINE_PAYMENT_BANK_ACCOUNTS_JSON", "[]")
OFFLINE_PAYMENT_PRIMARY_IBAN_ID = os.environ.get("OFFLINE_PAYMENT_PRIMARY_IBAN_ID", "IBAN_01")
OFFLINE_PAYMENT_RECEIPT_MAX_SIZE_MB = int(os.environ.get("OFFLINE_PAYMENT_RECEIPT_MAX_SIZE_MB", "5"))
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/1")
CELERY_TASK_IGNORE_RESULT = True
CELERY_TIMEZONE = "Asia/Tehran"
CELERY_BEAT_SCHEDULE = {
    "offline-payments-check-deadlines": {
        "task": "offline_payments.tasks.check_payment_deadlines",
        "schedule": 60.0,
    },
    "offline-payments-send-deadline-reminders": {
        "task": "offline_payments.tasks.send_payment_deadline_reminders",
        "schedule": 60.0,
    },
    "sales-expire-delivery-offers": {
        "task": "sales.tasks.expire_delivery_offers",
        "schedule": 60.0,
    },
}
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "staff"
CKEDITOR_5_MAX_FILE_SIZE = int(os.environ.get("CKEDITOR_5_MAX_FILE_SIZE_MB", 5))
CKEDITOR_5_UPLOAD_FILE_TYPES = ["jpg", "jpeg", "png", "gif", "bmp", "webp", "tiff"]
CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": {
            "items": [
                "heading",
                "|",
                "bold",
                "italic",
                "underline",
                "strikethrough",
                "link",
                "|",
                "bulletedList",
                "numberedList",
                "blockQuote",
                "|",
                "insertTable",
                "imageUpload",
                "mediaEmbed",
                "|",
                "undo",
                "redo",
            ],
            "shouldNotGroupWhenFull": True,
        },
        "image": {
            "toolbar": [
                "imageTextAlternative",
                "toggleImageCaption",
                "|",
                "imageStyle:inline",
                "imageStyle:block",
                "imageStyle:side",
            ],
        },
        "table": {
            "contentToolbar": [
                "tableColumn",
                "tableRow",
                "mergeTableCells",
                "tableProperties",
                "tableCellProperties",
            ],
        },
    },
}
