# Generated by Django 5.0.1 on 2026-06-29 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_remap_legacy_stages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='ارسالِ پیامک فعال است')),
                ('provider', models.CharField(choices=[('kavenegar', 'کاوه\u200cنگار')], default='kavenegar', max_length=20, verbose_name='سرویس\u200cدهنده')),
                ('kavenegar_api_key', models.CharField(blank=True, default='', max_length=255, verbose_name='کلید API کاوه\u200cنگار')),
                ('sender', models.CharField(blank=True, default='', help_text='شمارهٔ خطِ پیش\u200cفرضِ ارسال برای پیامکِ متنی (sms/send). خالی ⇒ خطِ پیش\u200cفرضِ حساب.', max_length=20, verbose_name='خطِ ارسال (اختیاری)')),
                ('default_template', models.CharField(blank=True, default='', help_text='نامِ الگوی verify/lookup برای پیامکِ تراکنشی (فیلترنشده). خالی ⇒ ارسالِ متنیِ ساده.', max_length=80, verbose_name='الگوی پیش\u200cفرض (lookup)')),
                ('purchase_template', models.CharField(blank=True, default='', help_text='نامِ الگوی verify/lookup برای پیامکِ مراحلِ خرید. خالی ⇒ ارسالِ متنیِ ساده.', max_length=80, verbose_name='الگوی مراحلِ خرید (lookup)')),
                ('daily_send_cap', models.PositiveIntegerField(default=0, help_text='حداکثر پیامکِ ارسالی در هر شبانه\u200cروز (محافظِ هزینه). صفر یعنی بدونِ محدودیت.', verbose_name='سقفِ ارسالِ روزانه')),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=64, verbose_name='کلید مخفیِ وب\u200cهوک')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات پیام\u200cرسانی',
                'verbose_name_plural': 'تنظیمات پیام\u200cرسانی',
            },
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'پیامک'), ('telegram', 'تلگرام'), ('whatsapp', 'واتساپ')], db_index=True, default='sms', max_length=12, verbose_name='کانال')),
                ('provider', models.CharField(blank=True, default='', max_length=20, verbose_name='سرویس\u200cدهنده')),
                ('recipient', models.CharField(db_index=True, max_length=32, verbose_name='گیرنده')),
                ('purpose', models.CharField(choices=[('manual', 'دستی'), ('bulk', 'گروهی'), ('order_status', 'مراحل خرید'), ('otp', 'کد یک\u200cبارمصرف')], db_index=True, default='manual', max_length=16, verbose_name='هدف')),
                ('template', models.CharField(blank=True, default='', max_length=80, verbose_name='الگو')),
                ('body', models.TextField(blank=True, default='', verbose_name='متن')),
                ('status', models.CharField(choices=[('queued', 'در صف'), ('sent', 'ارسال شد'), ('delivered', 'رسید به گیرنده'), ('failed', 'ناموفق'), ('skipped', 'نادیده (خشک)')], db_index=True, default='queued', max_length=12, verbose_name='وضعیت')),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=64, verbose_name='شناسهٔ پیام نزدِ سرویس')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='هزینه (ریال)')),
                ('error', models.CharField(blank=True, default='', max_length=400, verbose_name='خطا')),
                ('meta', models.JSONField(blank=True, null=True, verbose_name='اطلاعاتِ اضافه')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='customers.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'پیامِ ارسالی',
                'verbose_name_plural': 'پیام\u200cهای ارسالی',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['customer', 'created_at'], name='messaging_o_custome_c4f9bd_idx'), models.Index(fields=['status', 'created_at'], name='messaging_o_status_dc79be_idx')],
            },
        ),
    ]
