# Generated by Django 5.0.1 on 2026-06-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagingsettings',
            name='admin_alert_phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='موبایلِ ادمین برای هشدارِ پیامکی'),
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='notify_on_chat_lead',
            field=models.BooleanField(default=True, verbose_name='خبر هنگام سرنخِ چت'),
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='notify_on_order',
            field=models.BooleanField(default=True, verbose_name='خبر هنگام ثبتِ سفارش'),
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='notify_on_signup',
            field=models.BooleanField(default=True, verbose_name='خبر هنگام ثبت\u200cنامِ کاربر'),
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='telegram_admin_chat_id',
            field=models.CharField(blank=True, default='', help_text='chat_id مقصدِ اطلاع\u200cرسانی؛ چند مقصد را با کاما جدا کن.', max_length=120, verbose_name='آیدیِ چتِ ادمین'),
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='توکنِ ربات تلگرام'),
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='telegram_enabled',
            field=models.BooleanField(default=False, verbose_name='اطلاع\u200cرسانیِ تلگرام فعال است'),
        ),
        migrations.AlterField(
            model_name='outboundmessage',
            name='purpose',
            field=models.CharField(choices=[('manual', 'دستی'), ('bulk', 'گروهی'), ('order_status', 'مراحل خرید'), ('otp', 'کد یک\u200cبارمصرف'), ('admin_alert', 'هشدار ادمین')], db_index=True, default='manual', max_length=16, verbose_name='هدف'),
        ),
    ]
