# Generated by Django 5.0.1 on 2026-06-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_messagingsettings_admin_alert_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagingsettings',
            name='telegram_api_base',
            field=models.CharField(blank=True, default='https://api.telegram.org', help_text='پیش\u200cفرض api.telegram.org؛ از داخلِ ایران یک واسط (Cloudflare Worker/پروکسی) بگذار.', max_length=200, verbose_name='ریشهٔ API تلگرام'),
        ),
    ]
