# Generated by Django 5.0.1 on 2026-06-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_messagingsettings_telegram_api_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagingsettings',
            name='bale_admin_user_ids',
            field=models.CharField(blank=True, default='', help_text='userIdهای مجاز برای دستورهای مدیریتی در چتِ خصوصی (با کاما). در گروهِ تنظیم\u200cشده خودبه\u200cخود مجاز است.', max_length=255, verbose_name='آیدیِ کاربریِ ادمین\u200cها (دستورها)'),
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='bale_webhook_enabled',
            field=models.BooleanField(default=False, verbose_name='ربات دوطرفه فعال است'),
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='site_base_url',
            field=models.CharField(blank=True, default='https://kavex.ir', help_text='برای ساختِ لینکِ محصول در پاسخِ ربات قیمت.', max_length=200, verbose_name='آدرسِ سایت'),
        ),
        migrations.AlterField(
            model_name='messagingsettings',
            name='telegram_api_base',
            field=models.CharField(blank=True, default='https://api.telegram.org', help_text='برای «بله»: https://tapi.bale.ai ؛ از داخلِ ایران یک واسط (Worker/پروکسی) برای تلگرام.', max_length=200, verbose_name='ریشهٔ API تلگرام'),
        ),
    ]
