# Generated by Django 5.0.1 on 2026-06-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_messagingsettings_bale_admin_user_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagingsettings',
            name='safir_access_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Api Access Key سفیر'),
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='safir_bot_id',
            field=models.CharField(blank=True, default='', help_text='شناسهٔ عددیِ بازویی که با آن پیام ارسال می\u200cشود.', max_length=40, verbose_name='شناسهٔ عددیِ ربات (bot_id)'),
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='safir_enabled',
            field=models.BooleanField(default=False, verbose_name='ارسالِ پیامِ بله (سفیر) فعال است'),
        ),
        migrations.AlterField(
            model_name='outboundmessage',
            name='channel',
            field=models.CharField(choices=[('sms', 'پیامک'), ('telegram', 'تلگرام'), ('bale', 'بله (سفیر)'), ('whatsapp', 'واتساپ')], db_index=True, default='sms', max_length=12, verbose_name='کانال'),
        ),
    ]
