# Generated by Django 5.0.1 on 2026-07-12 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_messagingsettings_safir_access_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaleUserBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bale_user_id', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='شناسه کاربر بله')),
                ('display_name', models.CharField(blank=True, default='', max_length=120, verbose_name='نام نمایشی بله')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bale_binding', to=settings.AUTH_USER_MODEL, verbose_name='کاربر سایت')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_bale_bindings', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده')),
            ],
            options={
                'verbose_name': 'اتصال کاربر بله',
                'verbose_name_plural': 'اتصال کاربران بله',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
