# Generated by Django 5.0.1 on 2026-07-14 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_product_interests'),
        ('messaging', '0006_baleuserbinding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingContactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='نام گروه')),
                ('source', models.CharField(choices=[('website', 'گروه سایت'), ('kavenegar', 'واردشده از کاوه\u200cنگار')], db_index=True, default='website', max_length=16, verbose_name='منبع')),
                ('kavenegar_tag', models.CharField(blank=True, default='', max_length=200, verbose_name='تگ کاوه\u200cنگار')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='توضیح')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_messaging_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'گروه پیام\u200cرسانی',
                'verbose_name_plural': 'گروه\u200cهای پیام\u200cرسانی',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MessagingContactGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=11, verbose_name='موبایل نرمال\u200cشده')),
                ('name', models.CharField(blank=True, default='', max_length=160, verbose_name='نام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messaging_group_memberships', to='customers.customer', verbose_name='مشتری CRM')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='messaging.messagingcontactgroup', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'عضو گروه پیام\u200cرسانی',
                'verbose_name_plural': 'اعضای گروه پیام\u200cرسانی',
                'ordering': ['name', 'phone', 'id'],
                'indexes': [models.Index(fields=['group', 'phone'], name='messaging_m_group_i_e7ced7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='messagingcontactgroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'phone'), name='messaging_unique_group_phone'),
        ),
    ]
