# Generated by Django 5.0.1 on 2026-08-15 12:48

from django.db import migrations, models


def migrate_site_base_url(apps, schema_editor):
    messaging_settings = apps.get_model('messaging', 'MessagingSettings')
    legacy_urls = [
        'http://kavex.ir',
        'http://kavex.ir/',
        'https://kavex.ir',
        'https://kavex.ir/',
        'http://www.kavex.ir',
        'http://www.kavex.ir/',
        'https://www.kavex.ir',
        'https://www.kavex.ir/',
    ]
    messaging_settings.objects.filter(site_base_url__in=legacy_urls).update(
        site_base_url='https://kavehmetal.com',
    )


def restore_site_base_url(apps, schema_editor):
    messaging_settings = apps.get_model('messaging', 'MessagingSettings')
    messaging_settings.objects.filter(site_base_url='https://kavehmetal.com').update(
        site_base_url='https://kavex.ir',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_messagingcontactgroup_messagingcontactgroupmember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagingsettings',
            name='site_base_url',
            field=models.CharField(blank=True, default='https://kavehmetal.com', help_text='برای ساختِ لینکِ محصول در پاسخِ ربات قیمت.', max_length=200, verbose_name='آدرسِ سایت'),
        ),
        migrations.RunPython(migrate_site_base_url, restore_site_base_url),
    ]
