# Generated by Django 5.0.1 on 2026-06-20 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='نام')),
                ('phone', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='موبایل')),
                ('company', models.CharField(blank=True, default='', max_length=200, verbose_name='شرکت')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='شهر')),
                ('province', models.CharField(blank=True, default='', max_length=100, verbose_name='استان')),
                ('note', models.TextField(blank=True, default='', verbose_name='یادداشت')),
                ('extra_phones', models.JSONField(blank=True, default=list, verbose_name='شماره\u200cهای دیگر')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_customer', to=settings.AUTH_USER_MODEL, verbose_name='کاربر سایت (اختیاری)')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('purchase', 'خرید'), ('payment', 'پرداخت'), ('adjustment', 'تعدیل/مانده اولیه')], db_index=True, default='purchase', max_length=12, verbose_name='نوع')),
                ('amount', models.BigIntegerField(help_text='برای خرید/پرداخت مثبت؛ تعدیل می\u200cتواند منفی باشد.', verbose_name='مبلغ (تومان)')),
                ('description', models.CharField(blank=True, default='', help_text='مثلاً «۲۰ تن میلگرد ۱۴ ذوب».', max_length=255, verbose_name='شرح')),
                ('occurred_at', models.DateTimeField(blank=True, help_text='تاریخِ واقعیِ خرید/پرداخت؛ خالی یعنی همین حالا.', null=True, verbose_name='تاریخ واقعی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customers.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'تراکنش مشتری',
                'verbose_name_plural': 'تراکنش\u200cهای مشتری',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='customers_c_name_f018e2_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company'], name='customers_c_company_b97478_idx'),
        ),
        migrations.AddIndex(
            model_name='customertransaction',
            index=models.Index(fields=['customer', 'kind'], name='customers_c_custome_f0cdf4_idx'),
        ),
    ]
