# Generated by Django 5.0.1 on 2026-06-20 20:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.CharField(choices=[('incoming_call', 'تماس ورودی'), ('referral', 'معرفی'), ('website', 'سایت'), ('instagram', 'اینستاگرام'), ('walk_in', 'مراجعه حضوری'), ('assistant', 'دستیار'), ('other', 'سایر')], db_index=True, default='other', max_length=16, verbose_name='منبع'),
        ),
        migrations.AddField(
            model_name='customer',
            name='stage',
            field=models.CharField(choices=[('lead', 'سرنخ'), ('contacted', 'در حال پیگیری'), ('active', 'مشتری فعال'), ('dormant', 'راکد'), ('lost', 'ازدست\u200cرفته')], db_index=True, default='lead', max_length=12, verbose_name='مرحله'),
        ),
        migrations.CreateModel(
            name='CustomerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('call', 'تماس'), ('message', 'پیام'), ('meeting', 'جلسه'), ('note', 'یادداشت')], db_index=True, default='call', max_length=10, verbose_name='نوع')),
                ('body', models.TextField(blank=True, default='', help_text='چه گفته شد / نتیجه چه بود.', verbose_name='شرح')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان تعامل')),
                ('follow_up_at', models.DateTimeField(blank=True, db_index=True, help_text='تاریخِ قدمِ بعدی؛ خالی یعنی پیگیری\u200cای زمان\u200cبندی نشده.', null=True, verbose_name='پیگیری بعدی')),
                ('follow_up_note', models.CharField(blank=True, default='', help_text='مثلاً «دوباره زنگ بزن و قیمت نهایی را بده».', max_length=255, verbose_name='شرحِ پیگیری')),
                ('follow_up_done', models.BooleanField(db_index=True, default=False, verbose_name='پیگیری انجام شد')),
                ('follow_up_done_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انجام پیگیری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='customers.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'فعالیت مشتری',
                'verbose_name_plural': 'فعالیت\u200cهای مشتری',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['customer', 'occurred_at'], name='customers_c_custome_1affe1_idx'), models.Index(fields=['follow_up_done', 'follow_up_at'], name='customers_c_follow__130af0_idx')],
            },
        ),
    ]
