# Generated by Django 5.0.1 on 2026-06-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_source_customer_stage_customeractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeractivity',
            name='stage_from',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='مرحلهٔ قبلی'),
        ),
        migrations.AddField(
            model_name='customeractivity',
            name='stage_to',
            field=models.CharField(blank=True, db_index=True, default='', max_length=12, verbose_name='مرحلهٔ جدید'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(choices=[('incoming_call', 'تماس ورودی'), ('referral', 'معرفی'), ('website', 'سایت'), ('instagram', 'اینستاگرام'), ('walk_in', 'مراجعه حضوری'), ('assistant', 'دستیار'), ('linkedin', 'لینکدین'), ('exhibition', 'نمایشگاه'), ('association', 'انجمن/سندیکا'), ('b2b_platform', 'پلتفرم B2B'), ('cold_call', 'تماس سرد'), ('field_sales', 'بازاریابی میدانی'), ('other', 'سایر')], db_index=True, default='other', max_length=16, verbose_name='منبع'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='stage',
            field=models.CharField(choices=[('new', 'سرنخ'), ('nurturing', 'پرورش/اعتمادسازی'), ('proposal', 'پیش\u200cفاکتور'), ('negotiation', 'مذاکره/قرارداد'), ('won', 'مشتری فعال'), ('loyal', 'وفادار'), ('lost', 'ازدست\u200cرفته')], db_index=True, default='new', max_length=12, verbose_name='مرحله'),
        ),
        migrations.AlterField(
            model_name='customeractivity',
            name='kind',
            field=models.CharField(choices=[('call', 'تماس'), ('message', 'پیام'), ('meeting', 'جلسه'), ('note', 'یادداشت'), ('stage', 'تغییر مرحله')], db_index=True, default='call', max_length=10, verbose_name='نوع'),
        ),
    ]
