# Generated by Django 5.0.1 on 2026-06-29 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remap_legacy_stages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='کاربری که این مشتری را ثبت کرده؛ خالی یعنی به\u200cصورتِ خودکار (سیستم) ساخته شده.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(choices=[('incoming_call', 'تماس ورودی'), ('referral', 'معرفی'), ('website', 'ثبت\u200cنام سایت'), ('store_purchase', 'خرید از سایت'), ('chat', 'چت فروش'), ('instagram', 'اینستاگرام'), ('walk_in', 'مراجعه حضوری'), ('assistant', 'دستیار'), ('linkedin', 'لینکدین'), ('exhibition', 'نمایشگاه'), ('association', 'انجمن/سندیکا'), ('b2b_platform', 'پلتفرم B2B'), ('cold_call', 'تماس سرد'), ('field_sales', 'بازاریابی میدانی'), ('other', 'سایر')], db_index=True, default='other', max_length=16, verbose_name='منبع'),
        ),
    ]
