# Generated by Django 5.0.1 on 2026-07-12 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_created_by_alter_customer_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='عنوان فرصت')),
                ('stage', models.CharField(choices=[('new_inquiry', 'استعلام جدید'), ('qualified', 'نیاز تکمیل\u200cشده'), ('pricing', 'قیمت\u200cگذاری و موجودی'), ('quote_sent', 'پیشنهاد ارسال\u200cشده'), ('payment_pending', 'در انتظار پرداخت'), ('fulfillment', 'اجرا، بارگیری و حمل'), ('won', 'فروش موفق'), ('lost', 'ازدست\u200cرفته')], db_index=True, default='new_inquiry', max_length=24, verbose_name='مرحله فرصت')),
                ('source_type', models.CharField(choices=[('manual', 'ثبت دستی'), ('assistant_inquiry', 'استعلام دستیار سایت'), ('store_order', 'سفارش مستقیم سایت'), ('bale', 'ربات بله')], db_index=True, default='manual', max_length=24, verbose_name='منبع فرصت')),
                ('source_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='شناسه رکورد منبع')),
                ('source_status', models.CharField(blank=True, default='', max_length=32, verbose_name='وضعیت منبع')),
                ('expected_value_irr', models.BigIntegerField(default=0, verbose_name='ارزش مورد انتظار (ریال)')),
                ('probability', models.PositiveSmallIntegerField(default=10, verbose_name='احتمال موفقیت')),
                ('need_details', models.TextField(blank=True, default='', verbose_name='شرح نیاز')),
                ('next_action', models.CharField(blank=True, default='', max_length=255, verbose_name='اقدام بعدی')),
                ('next_follow_up_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='پیگیری بعدی')),
                ('lost_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='دلیل شکست')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات منبع')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='زمان بسته\u200cشدن')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_created_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='customers.customer', verbose_name='مشتری')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_owned_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='مسئول فروش')),
            ],
            options={
                'verbose_name': 'فرصت فروش',
                'verbose_name_plural': 'فرصت\u200cهای فروش',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CrmOpportunityStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, default='', max_length=24, verbose_name='مرحله قبلی')),
                ('to_stage', models.CharField(db_index=True, max_length=24, verbose_name='مرحله جدید')),
                ('event', models.CharField(blank=True, default='', max_length=80, verbose_name='رویداد')),
                ('event_key', models.CharField(blank=True, max_length=180, null=True, unique=True, verbose_name='کلید یکتای رویداد')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='دلیل')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات رویداد')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کاربر عامل')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='customers.crmopportunity', verbose_name='فرصت')),
            ],
            options={
                'verbose_name': 'تاریخچه مرحله فرصت',
                'verbose_name_plural': 'تاریخچه مراحل فرصت\u200cها',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CrmSyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('manual', 'ثبت دستی'), ('assistant_inquiry', 'استعلام دستیار سایت'), ('store_order', 'سفارش مستقیم سایت'), ('bale', 'ربات بله')], db_index=True, max_length=24)),
                ('source_id', models.CharField(db_index=True, max_length=64)),
                ('event_key', models.CharField(max_length=180, unique=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processed', 'انجام\u200cشده'), ('failed', 'ناموفق')], db_index=True, default='pending', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رویداد همگام\u200cسازی CRM',
                'verbose_name_plural': 'رویدادهای همگام\u200cسازی CRM',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'updated_at'], name='customers_c_status_90d1a8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='crmopportunity',
            index=models.Index(fields=['source_type', 'source_id'], name='customers_c_source__35075d_idx'),
        ),
        migrations.AddIndex(
            model_name='crmopportunity',
            index=models.Index(fields=['stage', 'updated_at'], name='customers_c_stage_934007_idx'),
        ),
        migrations.AddIndex(
            model_name='crmopportunity',
            index=models.Index(fields=['owner', 'stage'], name='customers_c_owner_i_b47c1f_idx'),
        ),
        migrations.AddConstraint(
            model_name='crmopportunity',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id', ''), _negated=True), fields=('source_type', 'source_id'), name='customers_unique_opportunity_source'),
        ),
        migrations.AddConstraint(
            model_name='crmopportunity',
            constraint=models.CheckConstraint(check=models.Q(('probability__gte', 0), ('probability__lte', 100)), name='customers_opportunity_probability_0_100'),
        ),
        migrations.AddIndex(
            model_name='crmopportunitystagehistory',
            index=models.Index(fields=['opportunity', 'created_at'], name='customers_c_opportu_954ea8_idx'),
        ),
    ]
