# Generated by Django 5.0.1 on 2026-07-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_backfill_site_opportunities'),
        ('products', '0017_productcategory_icon_image_productcategory_icon_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='product_interests',
            field=models.ManyToManyField(blank=True, related_name='crm_consumers', to='products.productcategory', verbose_name='دسته\u200cهای محصول مصرفی'),
        ),
    ]
