# Generated by Django 5.0.1 on 2026-06-15 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('qa', 'پرسش و پاسخ'), ('article', 'مقاله / متن آزاد')], default='qa', max_length=12)),
                ('topic', models.CharField(blank=True, default='عمومی', max_length=80)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('question', models.TextField(blank=True, default='')),
                ('answer', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=80)),
                ('embedded_hash', models.CharField(blank=True, default='', max_length=64)),
                ('embedded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دانش دستیار',
                'verbose_name_plural': 'دانش دستیار',
                'ordering': ['topic', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssistantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('assistant_name', models.CharField(default='مشاور فروش', max_length=80)),
                ('greeting', models.TextField(blank=True, default='سلام 👋 من مشاور فروش فولاد هستم. بفرمایید چه محصولی نیاز دارید (نوع، گرید، ضخامت/ابعاد و مقدار) تا بهترین گزینه و قیمت را برایتان پیدا کنم.')),
                ('persona', models.TextField(blank=True, default='تو «مشاور فروش» فروشگاه آنلاین آهن و فولاد هستی؛ یک کارشناسِ باتجربهٔ فروشِ تجهیزات و مقاطع صنعتی (ورق، رول، تیرآهن، میلگرد، لوله، پروفیل، شمش). لحن تو حرفه\u200cای، مودب، دقیق و کوتاه است و همیشه فارسی پاسخ می\u200cدهی.\nاصول کاری:\n- فقط بر اساس «دانش فروشگاه»، کاتالوگ محصولات و قیمت\u200cهای واقعی پاسخ بده؛ چیزی از خودت نساز.\n- اگر قیمت یا موجودیِ دقیق را نمی\u200cدانی، صادقانه بگو و کاربر را به «استعلام قیمت» یا تماس راهنمایی کن.\n- واحدها را دقیق بیان کن (میلی\u200cمتر، کیلوگرم، تن، تومان) و اعداد را خوانا بنویس.\n- برای انتخاب درست، نیاز کاربر را بفهم (نوع کالا، گرید/آلیاژ، ضخامت/ابعاد، مقدار، محل تحویل).\n- هیچ\u200cوقت ادعای قطعیِ تحویل/زمان/تخفیف نکن مگر در دانش آمده باشد.')),
                ('sales_workflow', models.TextField(blank=True, default='گردش\u200cکار فروش را گام\u200cبه\u200cگام دنبال کن:\n۱) خوش\u200cآمد کوتاه و پرسیدن نیاز مشتری (چه محصولی، چه گرید/ابعادی، چه مقدار).\n۲) با ابزار جستجوی محصول، گزینه\u200cهای مناسب را پیدا کن و خلاصه و شفاف معرفی کن (با لینک محصول).\n۳) اگر قیمت خواست، با ابزار قیمت، برآورد قیمت/وزن را بده و شرایط (محل تحویل، ارزش افزوده) را توضیح بده.\n۴) وقتی مشتری تمایل به خرید/استعلام داشت، نام و شمارهٔ موبایلش را مودبانه بگیر و با ابزار ثبت سرنخ ذخیره کن.\n۵) در پایان، مسیر ادامهٔ کار را بگو: «استعلام قیمت»/«خرید» در صفحهٔ محصول یا تماس با کارشناس.\nاگر سوال خارج از حوزهٔ فروش فولاد بود، مودبانه به موضوع فروش برگرد.')),
                ('openai_base_url', models.CharField(default='https://api.openai.com/v1', max_length=255)),
                ('chat_model', models.CharField(default='gpt-4o-mini', max_length=80)),
                ('embedding_model', models.CharField(default='text-embedding-3-small', max_length=80)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.3, max_digits=3)),
                ('max_context_chunks', models.PositiveSmallIntegerField(default=6)),
                ('max_tool_iterations', models.PositiveSmallIntegerField(default=4)),
                ('lead_capture_enabled', models.BooleanField(default=True)),
                ('handoff_phone', models.CharField(blank=True, default='', max_length=30)),
                ('handoff_note', models.CharField(blank=True, default='برای مشاورهٔ تخصصی با کارشناس تماس بگیرید.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات دستیار فروش',
                'verbose_name_plural': 'تنظیمات دستیار فروش',
            },
        ),
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('open', 'باز'), ('lead', 'سرنخ'), ('closed', 'بسته')], default='open', max_length=10)),
                ('lead_name', models.CharField(blank=True, default='', max_length=120)),
                ('lead_phone', models.CharField(blank=True, default='', max_length=30)),
                ('lead_interest', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'گفتگوی دستیار',
                'verbose_name_plural': 'گفتگوهای دستیار',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'کاربر'), ('assistant', 'دستیار'), ('tool', 'ابزار')], max_length=12)),
                ('content', models.TextField(blank=True, default='')),
                ('tool_name', models.CharField(blank=True, default='', max_length=60)),
                ('tool_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.assistantconversation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
