# Generated by Django 5.0.1 on 2026-06-18 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
        ('products', '0016_product_purchase_terms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.CharField(blank=True, default='', max_length=60)),
                ('grade', models.CharField(blank=True, default='', max_length=60)),
                ('factory', models.CharField(blank=True, default='', max_length=80)),
                ('quantity', models.CharField(blank=True, default='', max_length=60)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('matched_price', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('contact_name', models.CharField(blank=True, default='', max_length=120)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('new', 'جدید'), ('quoted', 'پیش\u200cفاکتور'), ('contacted', 'پیگیری\u200cشده'), ('won', 'موفق'), ('lost', 'ازدست\u200cرفته')], default='new', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='assistant.assistantconversation')),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.product')),
            ],
            options={
                'verbose_name': 'استعلام ساختاریافته',
                'verbose_name_plural': 'استعلام\u200cهای ساختاریافته',
                'ordering': ['-created_at'],
            },
        ),
    ]
