# Generated by Django 5.0.1 on 2026-06-26 12:14

from django.db import migrations, models

OLD_DEFAULT = "https://api.openai.com/v1"
NEW_DEFAULT = "https://api.avalai.ir/v1"


def flip_stale_base_url(apps, schema_editor):
    """ردیفِ موجود اگر هنوز روی پیش‌فرضِ قدیمیِ OpenAI (غیرقابل‌دسترس از ایران) باشد،
    به AvalAI منتقل شود تا دستیار فروش بدون تنظیمِ دستی هم کار کند."""
    AssistantSettings = apps.get_model("assistant", "AssistantSettings")
    AssistantSettings.objects.filter(openai_base_url=OLD_DEFAULT).update(openai_base_url=NEW_DEFAULT)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_assistantinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantsettings',
            name='openai_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assistantsettings',
            name='openai_base_url',
            field=models.CharField(default='https://api.avalai.ir/v1', max_length=255),
        ),
        migrations.RunPython(flip_stale_base_url, noop),
    ]
