# Generated by Django 5.0.1 on 2026-06-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_assistantsettings_openai_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantsettings',
            name='lead_capture_mode',
            field=models.CharField(choices=[('off', 'خاموش (فقط در صورتِ تمایلِ مشتری)'), ('soft', 'ترغیبی (اصرارِ مودبانه و پیگیر)'), ('strict', 'اجباری (قیمت فقط بعد از گرفتنِ نام و موبایل)')], default='soft', help_text='ترغیبی: با تاکتیکِ منفعت اصرار می\u200cکند. اجباری: قیمتِ دقیق را تا ثبتِ نام و موبایل نمی\u200cدهد.', max_length=8, verbose_name='حالتِ گرفتنِ مشخصات'),
        ),
    ]
