# Generated by Django 5.0.1 on 2026-01-20 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_alter_offer_created_at_alter_product_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('OFFER_SELECTED', 'OFFER_SELECTED'), ('DEPOSIT_PENDING', 'DEPOSIT_PENDING'), ('DEPOSIT_PAID', 'DEPOSIT_PAID'), ('PROVIDER_CONFIRMED', 'PROVIDER_CONFIRMED'), ('PAYMENT_IN_PROGRESS', 'PAYMENT_IN_PROGRESS'), ('READY_FOR_PICKUP', 'READY_FOR_PICKUP'), ('LOADING', 'LOADING'), ('LOADED_AWAITING_WEIGHT', 'LOADED_AWAITING_WEIGHT'), ('AWAITING_FINAL_PAYMENT', 'AWAITING_FINAL_PAYMENT'), ('READY_FOR_DELIVERY', 'READY_FOR_DELIVERY'), ('IN_TRANSIT', 'IN_TRANSIT'), ('DELIVERED', 'DELIVERED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='OPEN', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity_unit', models.CharField(blank=True, max_length=20)),
                ('approx_weight_kg', models.IntegerField(blank=True, null=True)),
                ('origin', models.JSONField(blank=True, null=True)),
                ('destination', models.JSONField(blank=True, null=True)),
                ('origin_city', models.CharField(blank=True, max_length=100)),
                ('destination_city', models.CharField(blank=True, max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('price_agreed_amount', models.BigIntegerField(blank=True, null=True)),
                ('price_agreed_currency', models.CharField(default='IRR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_orders', to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_orders', to=settings.AUTH_USER_MODEL)),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='OrderOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_total_amount', models.BigIntegerField()),
                ('price_total_currency', models.CharField(default='IRR', max_length=10)),
                ('price_unit_amount', models.BigIntegerField(blank=True, null=True)),
                ('price_unit_currency', models.CharField(default='IRR', max_length=10)),
                ('deposit_percent', models.IntegerField(blank=True, null=True)),
                ('lead_time_days', models.IntegerField(blank=True, null=True)),
                ('terms', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('DECLINED', 'DECLINED'), ('WITHDRAWN', 'WITHDRAWN')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_offers', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='orders.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='selected_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_orders', to='orders.orderoffer'),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=32, null=True)),
                ('to_status', models.CharField(max_length=32)),
                ('event', models.CharField(max_length=50)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
        ),
    ]
