# Generated by Django 5.0.1 on 2026-02-14 19:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0004_alter_offer_created_at_alter_product_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING_WAREHOUSE', 'PENDING_WAREHOUSE'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('DEACTIVATED', 'DEACTIVATED'), ('COMPLETED', 'COMPLETED')], db_index=True, default='DRAFT', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('product_title', models.CharField(blank=True, max_length=255)),
                ('grade', models.CharField(blank=True, max_length=64)),
                ('dimensions', models.CharField(blank=True, max_length=128)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity_unit', models.CharField(blank=True, max_length=20)),
                ('target_price_amount', models.BigIntegerField(blank=True, null=True)),
                ('target_price_currency', models.CharField(default='IRR', max_length=10)),
                ('loading_city', models.CharField(blank=True, max_length=100)),
                ('unloading_city', models.CharField(blank=True, max_length=100)),
                ('loading_location', models.TextField(blank=True)),
                ('unloading_location', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('warehouse_reject_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_requests', to='products.productcategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_order_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderRequestAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='orders.orderrequest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderRequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='order_request_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='orders.orderrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderRequestNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.orderrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_request_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderRequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=32, null=True)),
                ('to_status', models.CharField(max_length=32)),
                ('event', models.CharField(max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.orderrequest')),
            ],
            options={
                'ordering': ('-at',),
            },
        ),
        migrations.AddIndex(
            model_name='orderrequest',
            index=models.Index(fields=['status', 'type', 'created_at'], name='orders_orde_status_04c0de_idx'),
        ),
    ]
