# Generated by Codex on 2026-02-17

from django.db import migrations, models


def forwards(apps, schema_editor):
    OrderRequest = apps.get_model("orders", "OrderRequest")
    OrderRequest.objects.filter(type="BUY", status="APPROVED").update(status="ACTIVE")


def backwards(apps, schema_editor):
    OrderRequest = apps.get_model("orders", "OrderRequest")
    OrderRequest.objects.filter(type="BUY", status="ACTIVE").update(status="APPROVED")


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderrequest_orderrequestauditlog_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "DRAFT"),
                    ("ACTIVE", "ACTIVE"),
                    ("PENDING_WAREHOUSE", "PENDING_WAREHOUSE"),
                    ("APPROVED", "APPROVED"),
                    ("REJECTED", "REJECTED"),
                    ("DEACTIVATED", "DEACTIVATED"),
                    ("COMPLETED", "COMPLETED"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=32,
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
