# Generated by Django 5.0.1 on 2026-05-23 07:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0012_seed_grade_dependencies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('QUOTE_REQUESTED', 'Quote requested'), ('PRICE_CONFIRMED', 'Price confirmed'), ('PAYMENT_PENDING', 'Payment pending'), ('PAID', 'Paid'), ('FULFILLMENT_PENDING', 'Fulfillment pending'), ('READY_FOR_PICKUP', 'Ready for pickup'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='DRAFT', max_length=32)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='UNPAID', max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('destination_province', models.CharField(blank=True, max_length=100)),
                ('destination_city', models.CharField(blank=True, max_length=100)),
                ('destination_address', models.TextField(blank=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('subtotal_amount', models.BigIntegerField(default=0)),
                ('total_amount', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='IRR', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StoreOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('seller_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('quantity_unit', models.CharField(default='ton', max_length=20)),
                ('unit_price_amount', models.BigIntegerField(blank=True, null=True)),
                ('total_price_amount', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='IRR', max_length=10)),
                ('product_snapshot', models.JSONField(blank=True, default=dict)),
                ('specification_snapshot', models.JSONField(blank=True, default=dict)),
                ('delivery_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_order_items', to='products.offer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.storeorder')),
                ('pricing_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_order_items', to='products.pricingtier')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_order_items', to='products.product')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='StoreOrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=32, null=True)),
                ('to_status', models.CharField(max_length=32)),
                ('event', models.CharField(max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='sales.storeorder')),
            ],
            options={
                'ordering': ('-at',),
            },
        ),
        migrations.CreateModel(
            name='StorePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('currency', models.CharField(default='IRR', max_length=10)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('provider_reference', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.storeorder')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['buyer', 'status', 'created_at'], name='sales_store_buyer_i_bf3be2_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['payment_status', 'created_at'], name='sales_store_payment_9006d9_idx'),
        ),
    ]
