# Generated by Django 5.0.1 on 2026-05-23 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='payment_due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='payment_link_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='payment_link_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='payment_link_sent_to',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='payment_link_token',
            field=models.CharField(blank=True, db_index=True, max_length=96),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='payment_link_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='StoreOrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('MANUAL', 'Manual')], default='SMS', max_length=20)),
                ('recipient', models.CharField(blank=True, max_length=120)),
                ('event', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sales.storeorder')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
