# Generated by Django 5.0.1 on 2026-05-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_storeorder_admin_notes_storeorder_payment_due_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='settlement_term_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='settlement_term_fee_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='weight_adjustment_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storeorderitem',
            name='estimated_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='storeorderitem',
            name='final_price_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeorderitem',
            name='final_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='storeorderitem',
            name='price_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='storeorderitem',
            name='weight_adjustment_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storeorderitem',
            name='quantity_unit',
            field=models.CharField(choices=[('ton', 'Ton'), ('kg', 'Kilogram'), ('sheet', 'Sheet count')], default='ton', max_length=20),
        ),
    ]
