# Generated by Django 5.0.1 on 2026-05-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_storeorder_settlement_term_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorderitem',
            name='price_basis',
            field=models.CharField(blank=True, default='ton', max_length=20),
        ),
        migrations.AddField(
            model_name='storeorderitem',
            name='selected_condition_label',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
