# Generated by Django 5.0.1 on 2026-05-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_storeorderitem_price_basis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='loading_permission_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='market_price_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='price_valid_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='proforma_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='risk_status',
            field=models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('BLOCKED', 'Blocked')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='source_price_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='stock_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
