# Generated by Django 5.0.1 on 2026-05-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_storeorder_loading_permission_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='quote_confirmation_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('AWAITING_ADMIN_QUOTE', 'Awaiting admin quote'), ('AWAITING_BUYER', 'Awaiting buyer confirmation'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], db_index=True, default='NOT_REQUIRED', max_length=32),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='quote_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='quote_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='quote_rejection_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='quote_rejection_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='storeorderitem',
            name='selection_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
