# Generated by Django 5.0.1 on 2026-05-27 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_storeorder_quote_confirmation_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='driver_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='logistics_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='StoreBuyerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_default', '-updated_at'),
                'indexes': [models.Index(fields=['buyer', 'is_default'], name='sales_store_buyer_i_7c302a_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreBuyerInvoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('buyer_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=160)),
                ('national_id', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('economic_code', models.CharField(blank=True, max_length=40)),
                ('registration_id', models.CharField(blank=True, max_length=40)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_invoice_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_default', '-updated_at'),
                'indexes': [models.Index(fields=['buyer', 'buyer_type', 'is_default'], name='sales_store_buyer_i_2393c2_idx')],
            },
        ),
    ]
