# Generated by Django 5.0.1 on 2026-06-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_storeorder_driver_name_storeorder_driver_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='payment_method',
            field=models.CharField(choices=[('payment_link', 'Payment link'), ('satna_offline', 'Offline Satna')], db_index=True, default='payment_link', max_length=24),
        ),
    ]
