# Generated by Django 5.0.1 on 2026-06-03 18:11

import django.db.models.deletion
import sales.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_storeorder_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDeliveryAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('ARRIVED_FOR_LOADING', 'Arrived for loading'), ('LOADED', 'Loaded'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered'), ('PROOF_SUBMITTED', 'Proof submitted'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACCEPTED', max_length=24)),
                ('load_sequence', models.PositiveSmallIntegerField(default=1)),
                ('planned_weight_kg', models.DecimalField(decimal_places=3, max_digits=12)),
                ('vehicle_type', models.CharField(blank=True, max_length=100)),
                ('vehicle_plate', models.CharField(blank=True, max_length=80)),
                ('driver_phone', models.CharField(blank=True, max_length=40)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_for_loading_at', models.DateTimeField(blank=True, null=True)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('in_transit_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('proof_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_delivery_assignments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignments', to='sales.storeorder')),
            ],
            options={
                'ordering': ('load_sequence', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='StoreDeliveryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('bill_of_lading', 'Bill of lading'), ('weighbridge', 'Weighbridge receipt'), ('delivery_receipt', 'Delivery receipt'), ('load_photo', 'Load photo'), ('other', 'Other')], default='other', max_length=32)),
                ('file', models.FileField(upload_to=sales.models.delivery_document_upload_path)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sales.storedeliveryassignment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_delivery_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StoreDeliveryOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OFFERED', 'Offered'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='OFFERED', max_length=16)),
                ('response_note', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_delivery_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='storedeliveryassignment',
            name='offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='sales.storedeliveryoffer'),
        ),
        migrations.CreateModel(
            name='StoreDeliveryRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PUBLISHED', 'Published'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PUBLISHED', max_length=24)),
                ('total_weight_kg', models.DecimalField(decimal_places=3, max_digits=12)),
                ('required_driver_count', models.PositiveSmallIntegerField(default=1)),
                ('accepted_driver_count', models.PositiveSmallIntegerField(default=0)),
                ('per_driver_weight_limit_kg', models.DecimalField(decimal_places=3, default=25000, max_digits=12)),
                ('vehicle_type', models.CharField(blank=True, max_length=100)),
                ('pickup_window_start', models.DateTimeField(blank=True, null=True)),
                ('pickup_window_end', models.DateTimeField(blank=True, null=True)),
                ('dispatch_deadline', models.DateTimeField(blank=True, null=True)),
                ('pickup_notes', models.TextField(blank=True)),
                ('dispatcher_notes', models.TextField(blank=True)),
                ('shipment_snapshot', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_requests', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_requests', to='sales.storeorder')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='storedeliveryoffer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='sales.storedeliveryrequest'),
        ),
        migrations.CreateModel(
            name='StoreDeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=80)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(blank=True, max_length=24)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sales.storedeliveryassignment')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sales.storedeliveryrequest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='storedeliveryassignment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='sales.storedeliveryrequest'),
        ),
        migrations.CreateModel(
            name='StoreOrderLoadingVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('driver_name', models.CharField(max_length=160)),
                ('driver_phone', models.CharField(blank=True, max_length=40)),
                ('vehicle_type', models.CharField(blank=True, max_length=100)),
                ('vehicle_plate', models.CharField(max_length=80)),
                ('planned_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('loaded_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_store_loading_vehicles', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading_vehicles', to='sales.storeorder')),
            ],
            options={
                'ordering': ('sequence', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StoreOrderWeighbridgeSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=sales.models.weighbridge_slip_upload_path)),
                ('slip_number', models.CharField(blank=True, max_length=80)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('loading_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighbridge_slips', to='sales.storeorderloadingvehicle')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weighbridge_slips', to='sales.storeorder')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_store_weighbridge_slips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='storedeliveryrequest',
            index=models.Index(fields=['order', 'status', 'created_at'], name='sales_store_order_i_ab04a0_idx'),
        ),
        migrations.AddIndex(
            model_name='storedeliveryrequest',
            index=models.Index(fields=['status', 'created_at'], name='sales_store_status_3fbfc3_idx'),
        ),
        migrations.AddIndex(
            model_name='storedeliveryoffer',
            index=models.Index(fields=['driver', 'status', 'created_at'], name='sales_store_driver__5c859b_idx'),
        ),
        migrations.AddIndex(
            model_name='storedeliveryoffer',
            index=models.Index(fields=['request', 'status'], name='sales_store_request_47e78a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storedeliveryoffer',
            unique_together={('request', 'driver')},
        ),
        migrations.AddIndex(
            model_name='storedeliveryassignment',
            index=models.Index(fields=['driver', 'status', 'created_at'], name='sales_store_driver__deede7_idx'),
        ),
        migrations.AddIndex(
            model_name='storedeliveryassignment',
            index=models.Index(fields=['order', 'status'], name='sales_store_order_i_13edf6_idx'),
        ),
        migrations.AddIndex(
            model_name='storedeliveryassignment',
            index=models.Index(fields=['request', 'status'], name='sales_store_request_4a6744_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storedeliveryassignment',
            unique_together={('request', 'driver')},
        ),
        migrations.AddIndex(
            model_name='storeorderloadingvehicle',
            index=models.Index(fields=['order', 'is_active', 'sequence'], name='sales_store_order_i_fdfb30_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorderweighbridgeslip',
            index=models.Index(fields=['order', 'created_at'], name='sales_store_order_i_d196ec_idx'),
        ),
    ]
