# Generated by Django 5.0.1 on 2026-06-03 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_storedeliveryassignment_storedeliverydocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDriverOperationalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(db_index=True, default=False)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('vehicle_type', models.CharField(blank=True, max_length=100)),
                ('vehicle_plate', models.CharField(blank=True, max_length=80)),
                ('capacity_kg', models.DecimalField(decimal_places=3, default=25000, max_digits=12)),
                ('service_radius_km', models.PositiveIntegerField(default=150)),
                ('current_province', models.CharField(blank=True, max_length=100)),
                ('current_city', models.CharField(blank=True, max_length=100)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('user__username', 'user_id'),
            },
        ),
        migrations.AddField(
            model_name='storedeliveryoffer',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='storedeliveryoffer',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='storedeliveryoffer',
            name='match_rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storedeliveryoffer',
            name='match_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='storedeliveryoffer',
            name='notification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='storedeliveryoffer',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storedeliveryrequest',
            name='auto_reassign_enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='storedeliveryrequest',
            name='max_candidate_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storedeliveryrequest',
            name='offer_ttl_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='storedeliveryrequest',
            name='pickup_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='storedeliveryrequest',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='storedeliveryrequest',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='storedeliveryrequest',
            name='pickup_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='storedeliveryrequest',
            name='search_radius_km',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddIndex(
            model_name='storedeliveryoffer',
            index=models.Index(fields=['status', 'expires_at'], name='sales_store_status_e8a90f_idx'),
        ),
        migrations.AddField(
            model_name='storedriveroperationalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storedriveroperationalprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_store_driver_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='storedriveroperationalprofile',
            index=models.Index(fields=['is_verified', 'is_available'], name='sales_store_is_veri_e672c1_idx'),
        ),
        migrations.AddIndex(
            model_name='storedriveroperationalprofile',
            index=models.Index(fields=['current_province', 'current_city'], name='sales_store_current_d2ce91_idx'),
        ),
    ]
