# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_userrole_role_add_carrier"),
        ("sales", "0010_storedriveroperationalprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeorder",
            name="destination_latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="storeorder",
            name="destination_longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="storedeliveryrequest",
            name="recipient_type",
            field=models.CharField(
                choices=[("ALL", "Drivers and carriers"), ("DRIVER", "Driver"), ("CARRIER", "Carrier")],
                db_index=True,
                default="ALL",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="storedeliveryrequest",
            name="pickup_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="storedeliveryrequest",
            name="destination_province",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="storedeliveryrequest",
            name="destination_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="storedeliveryrequest",
            name="destination_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="storedeliveryrequest",
            name="destination_latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="storedeliveryrequest",
            name="destination_longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="storedeliveryoffer",
            name="recipient_type",
            field=models.CharField(
                choices=[("ALL", "Drivers and carriers"), ("DRIVER", "Driver"), ("CARRIER", "Carrier")],
                db_index=True,
                default="DRIVER",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="storedeliveryassignment",
            name="recipient_type",
            field=models.CharField(
                choices=[("ALL", "Drivers and carriers"), ("DRIVER", "Driver"), ("CARRIER", "Carrier")],
                db_index=True,
                default="DRIVER",
                max_length=16,
            ),
        ),
    ]
