# Generated by Django 5.0.1 on 2026-06-06 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_direct_sales_freight_dispatch_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightBidInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('DECLINED', 'Declined'), ('QUOTED', 'Quote submitted')], db_index=True, default='INVITED', max_length=12)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_bid_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('invited_at',),
            },
        ),
        migrations.CreateModel(
            name='FreightBidOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('invite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='sales.freightbidinvite')),
            ],
        ),
        migrations.CreateModel(
            name='FreightBidSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('AWARDED', 'Awarded'), ('BUYER_CONFIRMED', 'Buyer confirmed'), ('BUYER_REJECTED', 'Buyer rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=20)),
                ('deadline_at', models.DateTimeField()),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_freight_bid_sessions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_bid_sessions', to='sales.storeorder')),
                ('winner_offer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_session', to='sales.freightbidoffer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='freightbidinvite',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='sales.freightbidsession'),
        ),
        migrations.AddIndex(
            model_name='freightbidsession',
            index=models.Index(fields=['order', 'status'], name='sales_freig_order_i_986508_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='freightbidinvite',
            unique_together={('session', 'carrier')},
        ),
    ]
