# Generated by Django 5.0.1 on 2026-06-07 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_freight_bid_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightRateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('year_label', models.CharField(default='1405', max_length=20)),
                ('base_rate_toman', models.DecimalField(decimal_places=0, default=1319, help_text='نرخ پایه تن-کیلومتر (تومان) — مصوبه شورای عالی هماهنگی ترابری', max_digits=10)),
                ('default_vehicle_coefficient', models.DecimalField(decimal_places=2, default=1, help_text='ضریب ناوگان برای انواع خودرویی که در جدول ضرایب نیستند', max_digits=4)),
                ('vehicle_coefficients', models.JSONField(blank=True, default=dict, help_text='نگاشت نوع خودرو به ضریب ناوگان، مثل {"تریلی": 1.5}')),
                ('admin_fee_percent', models.DecimalField(decimal_places=2, default=4, help_text='کارمزد سازمان راهداری به درصد، روی کرایه خالص اعمال می\u200cشود', max_digits=5)),
                ('minimum_amount_toman', models.DecimalField(decimal_places=0, default=500000, help_text='حداقل کرایه قابل پیشنهاد (تومان)', max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تنظیمات نرخ حمل',
                'verbose_name_plural': 'تنظیمات نرخ حمل',
            },
        ),
    ]
