# Generated by Django 5.0.1 on 2025-10-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productstandard_specificationattribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='height_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
