# Generated by Django 5.0.1 on 2025-10-30 20:57

import products.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productspecification_height_mm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=products.models.JalaliDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=products.models.JalaliDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=products.models.JalaliDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='created_at',
            field=products.models.JalaliDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='updated_at',
            field=products.models.JalaliDateTimeField(auto_now=True),
        ),
    ]
