# Generated by Django 5.0.1 on 2026-05-08 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_offer_created_at_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylocation',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliverylocation',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='code',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product_kind',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='required_spec_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='spec_defaults',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='diameter_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ProductAttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=160)),
                ('product_kind', models.CharField(blank=True, default='', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_options', to='products.productcategory')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productattributeoption')),
            ],
            options={
                'ordering': ('group', 'sort_order', 'label'),
            },
        ),
        migrations.AddConstraint(
            model_name='productattributeoption',
            constraint=models.UniqueConstraint(fields=('group', 'value', 'parent'), name='uniq_product_option_group_value_parent'),
        ),
    ]
