# Generated by Django 5.0.1 on 2026-05-08 04:58

from django.db import migrations
from django.db.models import Max


def upsert_category(
    ProductCategory,
    *,
    name,
    code,
    parent=None,
    product_kind="",
    spec_defaults=None,
    required_spec_fields=None,
    sort_order=0,
    tree_id=None,
    lft=None,
    rght=None,
    level=0,
):
    defaults = {
        "code": code,
        "parent": parent,
        "product_kind": product_kind,
        "spec_defaults": spec_defaults or {},
        "required_spec_fields": required_spec_fields or [],
        "sort_order": sort_order,
        "is_active": True,
    }
    if tree_id is not None and lft is not None and rght is not None:
        defaults.update(
            {
                "tree_id": tree_id,
                "lft": lft,
                "rght": rght,
                "level": level,
            }
        )
    category, _ = ProductCategory.objects.update_or_create(
        name=name,
        defaults=defaults,
    )
    return category


def upsert_option(ProductAttributeOption, *, group, value, label, product_kind="", category=None, parent=None, sort_order=0):
    option, _ = ProductAttributeOption.objects.update_or_create(
        group=group,
        value=value,
        parent=parent,
        defaults={
            "label": label,
            "product_kind": product_kind,
            "category": category,
            "sort_order": sort_order,
            "is_active": True,
        },
    )
    return option


def seed_product_taxonomy(apps, schema_editor):
    ProductCategory = apps.get_model("products", "ProductCategory")
    ProductAttributeOption = apps.get_model("products", "ProductAttributeOption")
    base_tree_id = ProductCategory.objects.aggregate(max_tree_id=Max("tree_id"))["max_tree_id"] or 0

    sheet = upsert_category(
        ProductCategory,
        name="ورق",
        code="sheet",
        product_kind="sheet",
        required_spec_fields=["steel_grade"],
        sort_order=10,
        tree_id=base_tree_id + 1,
        lft=1,
        rght=22,
        level=0,
    )
    rebar = upsert_category(
        ProductCategory,
        name="میلگرد",
        code="rebar",
        product_kind="rebar",
        required_spec_fields=["steel_grade", "diameter_mm"],
        sort_order=20,
        tree_id=base_tree_id + 2,
        lft=1,
        rght=6,
        level=0,
    )
    profile = upsert_category(
        ProductCategory,
        name="قوطی و پروفیل",
        code="profile",
        product_kind="profile",
        required_spec_fields=["width_mm", "height_mm", "thickness_mm"],
        sort_order=30,
        tree_id=base_tree_id + 3,
        lft=1,
        rght=4,
        level=0,
    )
    pipe = upsert_category(
        ProductCategory,
        name="لوله",
        code="pipe",
        product_kind="pipe",
        required_spec_fields=["diameter_mm", "thickness_mm"],
        sort_order=40,
        tree_id=base_tree_id + 4,
        lft=1,
        rght=4,
        level=0,
    )
    beam = upsert_category(
        ProductCategory,
        name="تیرآهن",
        code="beam",
        product_kind="beam",
        required_spec_fields=["steel_grade"],
        sort_order=50,
        tree_id=base_tree_id + 5,
        lft=1,
        rght=4,
        level=0,
    )

    black_sheet = upsert_category(
        ProductCategory,
        name="ورق سیاه",
        code="sheet-black",
        parent=sheet,
        product_kind="sheet",
        spec_defaults={
            "material_type": "sheet",
            "steel_grade": "ST37",
            "surface_finish": "black",
        },
        required_spec_fields=["thickness_mm", "width_mm"],
        sort_order=10,
        tree_id=base_tree_id + 1,
        lft=2,
        rght=13,
        level=1,
    )
    upsert_category(
        ProductCategory,
        name="ورق روغنی",
        code="sheet-oiled",
        parent=sheet,
        product_kind="sheet",
        spec_defaults={"material_type": "sheet", "surface_finish": "oiled"},
        required_spec_fields=["steel_grade", "thickness_mm", "width_mm"],
        sort_order=20,
        tree_id=base_tree_id + 1,
        lft=14,
        rght=15,
        level=1,
    )
    upsert_category(
        ProductCategory,
        name="ورق آلیاژی",
        code="sheet-alloy",
        parent=sheet,
        product_kind="sheet",
        spec_defaults={"material_type": "sheet", "surface_finish": "alloy"},
        required_spec_fields=["steel_grade", "thickness_mm", "width_mm"],
        sort_order=30,
        tree_id=base_tree_id + 1,
        lft=16,
        rght=17,
        level=1,
    )
    upsert_category(
        ProductCategory,
        name="ورق رنگی",
        code="sheet-color",
        parent=sheet,
        product_kind="sheet",
        spec_defaults={"material_type": "sheet", "surface_finish": "color"},
        required_spec_fields=["steel_grade", "thickness_mm", "width_mm"],
        sort_order=40,
        tree_id=base_tree_id + 1,
        lft=18,
        rght=19,
        level=1,
    )
    upsert_category(
        ProductCategory,
        name="ورق گالوانیزه",
        code="sheet-galvanized",
        parent=sheet,
        product_kind="sheet",
        spec_defaults={"material_type": "sheet", "surface_finish": "galvanized"},
        required_spec_fields=["steel_grade", "thickness_mm", "width_mm"],
        sort_order=50,
        tree_id=base_tree_id + 1,
        lft=20,
        rght=21,
        level=1,
    )

    for sort_order, name, code, process, lft, rght in [
        (10, "ورق مبارکه", "sheet-black-mobarakeh", "sheet", 3, 4),
        (20, "رول مبارکه", "sheet-black-mobarakeh-coil", "coil", 5, 6),
        (30, "ورق آتیه", "sheet-black-atieh", "sheet", 7, 8),
        (40, "ورق اکسین", "sheet-black-oxin", "sheet", 9, 10),
        (50, "ورق خرم آباد", "sheet-black-khorramabad", "sheet", 11, 12),
    ]:
        upsert_category(
            ProductCategory,
            name=name,
            code=code,
            parent=black_sheet,
            product_kind="sheet",
            spec_defaults={"manufacturing_process": process},
            sort_order=sort_order,
            tree_id=base_tree_id + 1,
            lft=lft,
            rght=rght,
            level=2,
        )

    upsert_category(
        ProductCategory,
        name="میلگرد آجدار",
        code="rebar-ribbed",
        parent=rebar,
        product_kind="rebar",
        spec_defaults={"material_type": "rebar", "surface_finish": "ribbed"},
        sort_order=10,
        tree_id=base_tree_id + 2,
        lft=2,
        rght=3,
        level=1,
    )
    upsert_category(
        ProductCategory,
        name="میلگرد ساده",
        code="rebar-plain",
        parent=rebar,
        product_kind="rebar",
        spec_defaults={"material_type": "rebar", "surface_finish": "plain"},
        sort_order=20,
        tree_id=base_tree_id + 2,
        lft=4,
        rght=5,
        level=1,
    )
    upsert_category(
        ProductCategory,
        name="پروفیل قوطی",
        code="profile-box",
        parent=profile,
        product_kind="profile",
        spec_defaults={"material_type": "profile", "surface_finish": "box"},
        sort_order=10,
        tree_id=base_tree_id + 3,
        lft=2,
        rght=3,
        level=1,
    )
    upsert_category(
        ProductCategory,
        name="لوله صنعتی",
        code="pipe-industrial",
        parent=pipe,
        product_kind="pipe",
        spec_defaults={"material_type": "pipe"},
        sort_order=10,
        tree_id=base_tree_id + 4,
        lft=2,
        rght=3,
        level=1,
    )
    upsert_category(
        ProductCategory,
        name="تیرآهن IPE",
        code="beam-ipe",
        parent=beam,
        product_kind="beam",
        spec_defaults={"material_type": "beam", "manufacturing_process": "ipe"},
        sort_order=10,
        tree_id=base_tree_id + 5,
        lft=2,
        rght=3,
        level=1,
    )

    for sort_order, value in enumerate(["ST37", "ST52", "CK45", "A516", "A283"], start=1):
        upsert_option(
            ProductAttributeOption,
            group="steel_grade",
            value=value,
            label=value,
            product_kind="sheet",
            sort_order=sort_order,
        )
    for sort_order, value, label in [
        (1, "black", "سیاه"),
        (2, "oiled", "روغنی"),
        (3, "alloy", "آلیاژی"),
        (4, "color", "رنگی"),
        (5, "galvanized", "گالوانیزه"),
        (6, "stainless", "استیل"),
    ]:
        upsert_option(
            ProductAttributeOption,
            group="surface_finish",
            value=value,
            label=label,
            product_kind="sheet",
            sort_order=sort_order,
        )
    for sort_order, value, label in [
        (1, "sheet", "شیت / برش خورده"),
        (2, "coil", "رول"),
    ]:
        upsert_option(
            ProductAttributeOption,
            group="manufacturing_process",
            value=value,
            label=label,
            product_kind="sheet",
            sort_order=sort_order,
        )
    for sort_order, value in enumerate(["A1", "A2", "A3", "A4"], start=1):
        upsert_option(
            ProductAttributeOption,
            group="steel_grade",
            value=value,
            label=value,
            product_kind="rebar",
            sort_order=sort_order,
        )

    provinces = [
        ("isfahan", "اصفهان", ["اصفهان", "مبارکه"]),
        ("tehran", "تهران", ["تهران"]),
        ("khuzestan", "خوزستان", ["اهواز"]),
        ("lorestan", "لرستان", ["خرم آباد"]),
        ("markazi", "مرکزی", ["اراک"]),
    ]
    for province_order, (province_value, province_label, cities) in enumerate(provinces, start=1):
        province = upsert_option(
            ProductAttributeOption,
            group="province",
            value=province_value,
            label=province_label,
            sort_order=province_order,
        )
        for city_order, city in enumerate(cities, start=1):
            upsert_option(
                ProductAttributeOption,
                group="city",
                value=city,
                label=city,
                parent=province,
                sort_order=city_order,
            )

    try:
        ProductCategory.objects.rebuild()
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_deliverylocation_address_deliverylocation_province_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_product_taxonomy, migrations.RunPython.noop),
    ]
