# Generated by Django 5.0.1 on 2026-05-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_seed_product_taxonomy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='material_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='steel_grade',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
