# Generated by Django 5.0.1 on 2026-05-19 20:28

from django.db import migrations, models


def upsert_option(ProductAttributeOption, *, group, value, label, product_kind="", parent=None, sort_order=0):
    ProductAttributeOption.objects.update_or_create(
        group=group,
        value=value,
        parent=parent,
        defaults={
            "label": label,
            "product_kind": product_kind,
            "sort_order": sort_order,
            "is_active": True,
        },
    )


def normalize_sheet_taxonomy(apps, schema_editor):
    ProductCategory = apps.get_model("products", "ProductCategory")
    ProductAttributeOption = apps.get_model("products", "ProductAttributeOption")

    ProductCategory.objects.filter(code="sheet").update(
        product_kind="sheet",
        spec_defaults={"material_type": "sheet"},
        required_spec_fields=["steel_grade"],
        is_active=True,
    )
    ProductCategory.objects.filter(
        code__in=[
            "sheet-black-mobarakeh",
            "sheet-black-mobarakeh-coil",
            "sheet-black-atieh",
            "sheet-black-oxin",
            "sheet-black-khorramabad",
        ]
    ).update(is_active=False)

    upsert_option(ProductAttributeOption, group="manufacturing_process", value="sheet", label="ورق", product_kind="sheet", sort_order=1)
    upsert_option(ProductAttributeOption, group="manufacturing_process", value="coil", label="رول", product_kind="sheet", sort_order=2)

    for sort_order, value, label in [
        (1, "black", "سیاه"),
        (2, "alloy", "آلیاژی"),
        (3, "acid_washed", "اسیدشویی"),
        (4, "oiled", "روغنی"),
        (5, "galvanized", "گالوانیزه"),
        (6, "color", "رنگی"),
        (7, "stainless", "استیل"),
    ]:
        upsert_option(
            ProductAttributeOption,
            group="surface_finish",
            value=value,
            label=label,
            product_kind="sheet",
            sort_order=sort_order,
        )

    sheet_option = ProductAttributeOption.objects.filter(group="manufacturing_process", value="sheet").first()
    coil_option = ProductAttributeOption.objects.filter(group="manufacturing_process", value="coil").first()
    factories = [
        ("mobarakeh", "فولاد مبارکه"),
        ("kavian", "کاویان"),
        ("khorramabad", "خرم آباد"),
        ("oxin", "اکسین"),
        ("atieh", "آتیه"),
    ]
    for sort_order, (value, label) in enumerate(factories, start=1):
        upsert_option(
            ProductAttributeOption,
            group="factory",
            value=value,
            label=label,
            product_kind="sheet",
            parent=sheet_option,
            sort_order=sort_order,
        )
        upsert_option(
            ProductAttributeOption,
            group="factory",
            value=value,
            label=label,
            product_kind="sheet",
            parent=coil_option,
            sort_order=sort_order,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='factory',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.RunPython(normalize_sheet_taxonomy, migrations.RunPython.noop),
    ]
