# Generated by Django 5.0.1 on 2026-05-21 08:53

from django.db import migrations, models


def upsert_option(ProductAttributeOption, *, group, value, label, product_kind="", parent=None, sort_order=0):
    ProductAttributeOption.objects.update_or_create(
        group=group,
        value=value,
        parent=parent,
        defaults={
            "label": label,
            "product_kind": product_kind,
            "sort_order": sort_order,
            "is_active": True,
        },
    )


def seed_product_display_options(apps, schema_editor):
    ProductAttributeOption = apps.get_model("products", "ProductAttributeOption")
    for sort_order, value, label in [
        (1, "factory", "فابریک"),
        (2, "cut", "برش خورده"),
    ]:
        upsert_option(
            ProductAttributeOption,
            group="cut_type",
            value=value,
            label=label,
            product_kind="sheet",
            sort_order=sort_order,
        )
    for sort_order, value, label in [
        (1, "factory", "کارخانه"),
        (2, "warehouse", "انبار"),
    ]:
        upsert_option(
            ProductAttributeOption,
            group="delivery_place",
            value=value,
            label=label,
            sort_order=sort_order,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productspecification_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability_status',
            field=models.CharField(choices=[('in_stock', 'In stock'), ('inquiry', 'Price inquiry'), ('out_of_stock', 'Out of stock')], default='in_stock', max_length=32),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='cut_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.RunPython(seed_product_display_options, migrations.RunPython.noop),
    ]
