# Generated by Django 5.0.1 on 2026-05-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_seed_grade_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingtier',
            name='condition_label',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='pricingtier',
            name='dimension_length_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricingtier',
            name='dimension_width_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricingtier',
            name='price_basis',
            field=models.CharField(choices=[('ton', 'Price per ton'), ('kg', 'Price per kilogram'), ('sheet', 'Price per sheet')], db_index=True, default='ton', max_length=20),
        ),
    ]
