# Generated by Django 5.0.1 on 2026-05-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_pricingtier_condition_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingtier',
            name='price_basis',
            field=models.CharField(choices=[('ton', 'Price per ton'), ('kg', 'Price per kilogram'), ('sheet', 'Price per sheet')], db_index=True, default='kg', max_length=20),
        ),
    ]
