# Generated by Django 5.0.1 on 2026-05-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_backfill_legacy_price_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_terms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='head_tail_policy',
            field=models.CharField(blank=True, choices=[('optional', 'Optional'), ('included', 'Included'), ('surcharge_if_excluded', 'Surcharge if excluded')], default='optional', max_length=32),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='sales_mode',
            field=models.CharField(blank=True, choices=[('sheet', 'Sheet'), ('coil_full', 'Full coil'), ('coil_cuttable', 'Cuttable coil'), ('coil_must_cut', 'Must-cut coil')], default='', max_length=32),
        ),
    ]
