# Generated by Django 5.0.1 on 2026-07-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_purchase_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/category-icons/'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='icon_key',
            field=models.CharField(blank=True, choices=[('layers', 'Layers'), ('sheet', 'Sheet'), ('rebar', 'Rebar'), ('beam', 'Beam'), ('pipe', 'Pipe'), ('profile', 'Profile'), ('billet', 'Billet'), ('coil', 'Coil'), ('ore', 'Ore'), ('scrap', 'Scrap'), ('recycle', 'Recycle'), ('factory', 'Factory'), ('cubes', 'Cubes'), ('package', 'Package')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='show_in_navigation',
            field=models.BooleanField(default=True),
        ),
    ]
