# Generated by Django 5.0.1 on 2026-08-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productcategory_icon_image_productcategory_icon_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingtier',
            name='price_verified_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, default='', max_length=320),
        ),
        migrations.AddField(
            model_name='product',
            name='page_h1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='related_by_products', symmetrical=False, to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_faqs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_index_mode',
            field=models.CharField(choices=[('auto', 'Automatic'), ('index', 'Index'), ('noindex', 'No index')], default='auto', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
